[package]
name = "audiophore-cli"
description = "Audiophore binary entry point."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[[bin]]
name = "audiophore"
path = "src/main.rs"

[dev-dependencies]
audiophore-core = { path = "../audiophore-core", version = "0.1" }
audiophore-adapter-core = { path = "../audiophore-adapter-core", version = "0.1" }
audiophore-adapter-sacn = { path = "../audiophore-adapter-sacn", version = "0.1" }
audiophore-audio = { path = "../audiophore-audio", version = "0.1" }
audiophore-engine = { path = "../audiophore-engine", version = "0.1" }
rosc = "0.11"
tokio = { version = "1", features = ["net", "rt", "rt-multi-thread", "macros", "sync", "time"] }
